name: CI

on: 
  pull_request:
    branches: master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'

      - name: Install dependencies
        run: npm install

      - name: Lint Code
        run: npm run ci:lint

      - name: Type Check
        run: npm run ci:type-check

      - name: Format Check
        run: npm run ci:format

      - name: Run Tests
        run: npm run test
